# Generated by Django 3.2.16 on 2023-04-26 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[6-9]/d{9}')]),
        ),
    ]
